### ISSUE TITLE
Easy way for change year 

### ISSUE THREAD

**Issue by felansu** [g1eb/angular-datetime-inputs#13]
Implement other way to change the year fast and easy

**Comment by g1eb** [comment]
Hi there! Thanks for your feedback, this could be a valuable feature! :)

Can you tell me something about your use case for this? And would you have any suggestions on how to add this functionality and keep the design clean and uncluttered? I could add something like a dropdown with other years but I can imagine that list will be essentially infinite.

P.S. have you tried scrolling over the 'months' calendar header to switch between months faster?

**Comment by felansu** [comment]
`P.S. have you tried scrolling over the 'months' calendar header to switch between months faster?`
- Yes, but if i need set the birth data ? (2017 - 1989) * 12 <- Mouse clicks

I think, the first option for user select is the year, month and day (in this order).
Maybe can show a grid with years options and next can select the month...

**Comment by g1eb** [comment]
Ahh I see. I can imagine scroll taking a while when you need to go back a couple years.

Put in a different context (e.g. selecting a date when booking a plane ticket) selecting a year is less important and often default behavior is that current year is automatically selected. Moreover, birthdates can have different formats in different countries and with that in mind I'd like to keep the input as generic as possible.

I'll have to think about this one. There has to be a way of adding easy input interaction for year selection and keeping the flow as simple as it is :)

**Comment by felansu** [comment]
nice example: https://krescruz.github.io/angular-materialize/#input-clock

**Comment by g1eb** [comment]
Interesting! Do you mean to use example of the clock to design something like that for year selection? Or the `Input-Date` one with years in a dropdown next to the month?

Have you seen this other material design datepicker demo with infinite scroll of years and months in something that opens over the main calendar widget?
[https://material.angularjs.org/latest/demo/datepicker](https://material.angularjs.org/latest/demo/datepicker)

**Comment by felansu** [comment]
https://material.angularjs.org/latest/demo/datepicker <- Nice 😃

**Comment by g1eb** [comment]
Good morning! :)
I've been thinking about how to solve this and came up with 2 potential features.

1. Add year display to the calendar header like `Month, Year` and switch years on hover + scroll similar to how changing months works when you hover over the calendar header and scroll with your mouse. The downside of this is that scrolling over months works fine now and would require a refactor to add the (maybe) less obvious scroll over years. Would this make year selection faster for you?

2. I have long wanted to make the time inputs editable on click, basically meaning that when you click on either hour/minute/second display it would turn into an input (or contenteditable span) and allow you to type the desired amount of hours/minutes/seconds. This would mean I could add something similar for date, e.g. when you click on `Month, Year` it would turn into an input and you would be able to type the desired month and/or year yourself. Downside of this is cross-browser compatibility and it would probably break custom validation of datetime inputs (not sure about this one).

On the other hand I understand if you prefer to use material design datepicker if it better meets your requirements. That's why we have different widgets for different purposes 😄
