### ISSUE TITLE
ScrollUP and Scrolldown events fired twice.

### ISSUE THREAD

**Issue by ShankzPatil** [g1eb/angular-datetime-inputs#20]
hi,

i observe that when i am using range and input both in my project ScrollUP and Scroll Down event fired twice. so whenever value changes multiple of +2 or -2.

**Comment by ShankzPatil** [comment]
any updates??

**Comment by g1eb** [comment]
Hey, this one got lost in my mail, i'll take a look at this right away :)

**Comment by g1eb** [comment]
Turns out, the support for scroll events is a small directive that is shipped in both `datetime-range` and `datetime-inputs` projects simultaneously. I guess this issue never came up before because people have not used those components on the same page. :)

There are two ways to fix this, either we integrate `datetime-range` together with other datetime inputs in a single library or take the scroll events out and make it a reusable utility.

I'm considering both options right now and will get back to you with an update shortly :)

**Comment by g1eb** [comment]
Okay, I decided to go with the second option and made scroll directives available as a separate library that both `datetime-range` and `datetime-inputs` can use. This update is available in the latest release, let me know if this works for you :)

v0.2.1

**Comment by ShankzPatil** [comment]
working fine.
